tunnel: cloudflare-tunnel-id
credentials-file: C:\Users\{username}\.cloudflared\cloudflare-tunnel-id.json

ingress:
  - hostname: example.com
    service: http://localhost:3000
  - hostname: socket.example.com
    service: http://localhost:3001
  - service: http_status:404